run:
  # default concurrency is a available CPU number
  concurrency: 8
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  deadline: 3m
  tests: true
  skip-dirs:
    - .bingo
    - .github
    - examples
    - jsonnet
    - vendor
linters:
  disable:
  - exhaustivestruct
  - exhaustruct
  - maintidx
  - nonamedreturns
  - gci
  - godot
  - nlreturn
  - nolintlint
  - testpackage
  - wrapcheck
  - gomoddirectives
  - ireturn
  - varnamelen
  - paralleltest
  - gocognit

linters-settings:
  errcheck:
    exclude-functions:
      - '(github.com/go-kit/log.Logger).Log'
  lll:
    line-length: 200
  funlen:
    lines: 210
    statements: 50
